services:
  redis-server:
    image: redis:8.0
    container_name: redis-server
    restart: always
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"
    env_file:
      - ".redis_env"
    command: redis-server --save 20 1 --loglevel warning

  postgres-db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ".postgres_env"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  redis_data:
  postgres_data:
