services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./users.conf:/etc/sftp/users.conf:roo
      - ./init.sh:/etc/sftp.d/init.sh:ro
      - /srv/allservers:/home
    ports:
      - "2222:22"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
